### ISSUE TITLE
More mining details?

### ISSUE THREAD

**Issue by vessenes** [grasslandnetwork/node_lite#2]
Hi, 

I’m super interested in your project. To be clear, I’m not sure building out a decentralized panopticon singularity type project with crypto incentivization is a *good* idea, but it definitely is interesting.

Do you have more reference to your data storage plans and mining / Proof of Work algorithm anywhere? The diagram in the short paper you put up leaves a lot of questions for me, including stuff like:

* do nodes share output data anywhere? If so, I can’t tell how all the output data is validated, only output data that goes into the final proof of work hash.
* It seems like you’re close to an algorithm which would let you prove certain data was generated by the AI network, but not quite there - that is, rather than just a merkle tree of hashes, it would be really useful if you could prove a certain data frame went through a certain version of your neural net after the fact. I can’t figure out how you can do this from your diagram though. 
* Have you done any work on the economic model beyond saying people will get it for mining, and use it to buy data from nodes? 
* Do you have any plans to decentralize the creation of each eon’s neural nets? 
* Might be nice to plan for re-running old data through new eon’s nets - I think over time that’s something you might want to incentivize. 

Thanks, Peter

**Comment by vessenes** [comment]
Related q - I note in your design spec document you mention that nodes are considered to be economically rational. 

If this is true, is there a reason nodes would not just offer randomized input ‘frames’ to the mining algorithm? It seems like it would be more efficient than actually getting video pushed through the bus, if only a little.

**Comment by 00hello** [comment]
> Hi,

Hi Peter

> I’m super interested in your project. To be clear, I’m not sure building out a decentralized panopticon singularity type project with crypto incentivization is a _good_ idea, but it definitely is interesting.

Uh... Thanks... (i think?).

> 
> Do you have more reference to your data storage plans and mining / Proof of Work algorithm anywhere? 

You'll see in the code that nodes use the geo-spatial indexing software [s2Geometry](http://s2geometry.io/) (written by Google and also used by those Pokemon people) to record the locations of tracked objects. It's designed for key-value storage databases like [LevelDB](http://leveldb.org/) and allows for much better performance than indexing by latitude/longitude. By fortunate coincidence, that's the very same database Bitcoin and many other cryptocurrencies use so I'll be using it for indexing the transactions as well. Anything that would need to be queried by the node will be stored in that database. Older entries can be stored in block files. 

Most nodes will obviously not be able to store the entire database, so there must obviously be nodes that can store it all. I intend to be one of them for as long as I can. 

I don't have more references to the algorithm besides what's in the code that's up now and in the code I hope to release in the next few days. The rest is written in my notebook/head and I haven't had time to make and post more nice diagrams and stuff.  But as of yesterday, there is no longer just one person writing the software so a lot of these tasks can be shared.


> * do nodes share output data anywhere? If so, I can’t tell how all the output data is validated, only output data that goes into the final proof of work hash.

They will share output data. [I've still got to push that](https://gist.github.com/00hello/0199d393e872ed7645979f5daf7bd62c). 

> * It seems like you’re close to an algorithm which would let you prove certain data was generated by the AI network, but not quite there - that is, rather than just a merkle tree of hashes, it would be really useful if you could prove a certain data frame went through a certain version of your neural net after the fact. I can’t figure out how you can do this from your diagram though.

That's all explained on the front page of the site under "Unrewriteable History And Reasonable Storage Requirements". To restate it here, the root of the next Merkle Tree will determine which of the published digest tuples will be required for evaluation by nodes who are doing the "mining". Those frame images are published by the nodes over [IPFS](https://en.wikipedia.org/wiki/InterPlanetary_File_System) being labelled and signed so as to be identified with the digest tuple corresponding with the object(s) [tracklet(s)](https://en.wiktionary.org/wiki/tracklet) that the node is claiming the current eon's detection model had correctly detected. The nodes 'mining'/'growing' the next Merkle Tree compete to verify that by performing inference on those frames using the same model.

Since the type of neural network we use is deterministic, as long as people are using the same NN model, consensus will be reached. Nodes are compelled therefore to use the same model. 

So we are proving that "a certain data frame went through a certain version of your neural net after the fact". That's how the whole thing works.

> * Have you done any work on the economic model beyond saying people will get it for mining, and use it to buy data from nodes?

"...saying people will ...use it to buy data from nodes" Uh... when and where could I possibly have said that? That would be like a bitcoin miner concealing the data that proves they've hashed the next block hoping that some day somebody will buy it from them. Nodes are broadcasting the object [tracklets](https://en.wiktionary.org/wiki/tracklet), the object's class and ID along with the the hashes of the frames from which they were taken, as I've described here and on the website.  

The data is what's being broadcast to other nodes. No one has to buy any data. It's free, in almost every sense of the word. That's part of the whole point. And selling the 'work' part of the proof-of-work doesn't make sense in such a system.


> * Do you have any plans to decentralize the creation of each eon’s neural nets?

[It's a cunning lure, I'll admit :)](http://www.reactiongifs.com/r/tbt.gif) But 'decentralisation extremism' can only ever be satisfied by some sort of infinitely regressing, decentralized-turtles all the way down vapourwear. Meanwhile, code never gets shipped and nothing ever gets decided upon because their users have been conditioned to expect that a perpetually increasing number of things _must_ be decentralized. A beast so hungry and confused that it devours itself. But I try to give my users rational and timely solutions to real problems. 

That other stuff is fine for other projects. I say to them, "fill your boots" (and your beasts!). That sort of thing. But I'm not about to lead my users and devs down a path of impractical/religious idealism whose promises can never actually get delivered on. 

The logical conclusions that one must necessarily deduce from the three postulates I defined on the site reveal a completely different type of beast. And wasting time circle-jerking is dangerous with what we're doing. All of us here have to either hurry to paddle out to meet the wave or get crushed by it. 

> * Might be nice to plan for re-running old data through new eon’s nets - I think over time that’s something you might want to incentivize.

No. That would require every single node cumulatively storing and doing inference on 4,000 to 5,000 hours worth of video. By the fourth eon, they'd each have to store and perform inference on a backlog of 16,000 to 20,0000 hours of video not to mention the live stream.  I don't see how that could ever work.

**Comment by 00hello** [comment]
> Related q - I note in your design spec document you mention that nodes are considered to be economically rational.
> 
> If this is true, is there a reason nodes would not just offer randomized input ‘frames’ to the mining algorithm? It seems like it would be more efficient than actually getting video pushed through the bus, if only a little.

That would be patently obvious to other nodes just on the broadcast of the object tracklets. If you've got people disappearing and reappearing, you've got cars half stuck in the ground, other cars driving through buildings or off into space, a dog floating 20 metres off the ground, that's going to be pretty easy to spot.

**Comment by 00hello** [comment]
Actually, it's much, much worse than that. If you randomize the input it'd just be noise. You'd be lucky to detect any object. It's not just that your homography wouldn't match up, there'd be no more buildings, no more cars, no more people etc etc. Everything you're supposed to detect would be gone.

**Comment by vessenes** [comment]
Just checking back in; I've been traveling. I don't want to stop you from working but would like to continue this conversation -- do you have a preferred way to get in touch that's not a github issue?

**Comment by 00hello** [comment]
> Just checking back in; I've been traveling. I don't want to stop you from working but would like to continue this conversation -- do you have a preferred way to get in touch that's not a github issue?

My contact info is listed on the front of the website (In the last bullet point and also above the GLn(F) logo) if you have broader inquiries about Grassland.  I'll be putting most questions I get of that nature into a F.A.Q. soon.

> david[at]grassland[dot]network

Github is just where I'd prefer software specific, technical issues/questions be raised since it'll be useful for future readers with similar technical inquiries.

**Comment by 00hello** [comment]
[Verifiable Computation Vs. Verifiable Data](https://medium.com/@davidrom/grassland-mining-verifiable-computation-vs-verifiable-data-9fa6af88c584)

I wanted to elaborate further on how 'mining' will work in the context of some of the attack methods you brought up in this issue. So I turned my explanation into a blog post on Medium. The link above will take you to it.

**Comment by 00hello** [comment]
Good news. Grassland has received funding for full time development! 

_I haven't set up a good system of broadcasting news to users yet (besides [my blog](https://medium.com/@davidrom/)) so I figured I'd also post it to this somewhat general issue/thread that I know people are following, before I close it_ 

A very well known organization and a major institution have seen what's already been accomplished with so little time and resources and despite that, still managing to solve some very old problems in AI, computer vision and cryptocurrencies. They're convinced enough that they've agreed to fund Grassland's further development.  

If you are or know anyone interested in joining the core team, please send them [this link to my Facebook post/announcement](https://www.facebook.com/dathompson/posts/10156257618892544)
